version: "3.8"

services:
  php:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.php.dev
    volumes:
      - ../:/var/www/html
    networks:
      - app-network

  node:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.node.dev
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"  # Vite dev server port
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
