FROM php:8.4-fpm

# Install dependencies required to compile ext-mongodb
RUN apt-get update && apt-get install -y libssl-dev \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

# Install Composer globally (using the official composer image)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

CMD ["php-fpm"]
