version: "3.8"

services:
  php_node:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.prod
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/prod/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../public:/var/www/html/public  # Adjust if your build outputs to a different folder
    ports:
      - "80:80"
    depends_on:
      - php_node
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - data:/data
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
