version: "3.8"

services:
  php:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.php.prod
    environment:
      - APP_ENV:""
    networks:
      - app-network

  node:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.node.prod
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/prod/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../public:/var/www/html/public  # Adjust if your build outputs to a different folder
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
