FROM node:22

WORKDIR /var/www/html

# Copy package files to leverage Docker caching
COPY package*.json ./
RUN npm install

# Copy the rest of the project and build assets
COPY . .
RUN npm run build

# In production, you might simply build assets and then serve them via Nginx.
CMD ["echo", "Node production build complete"]
